default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: action_mailer_development

test:
  <<: *default
  database: action_mailer_development

production:
  <<: *default
  database: action_mailer_development
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock